#!/usr/bin/env python3
"""
problem_index.py — a derived, disposable map of the vault's problem notes.

Both Ingest (dedup before create) and Connect (find unlinked neighbours)
need a cheap, current answer to: "what problems already exist, and what do
they link to?" This script produces exactly that by scanning note bodies.

It is NOT a source of truth. Markdown is the database. This index is
regenerated by re-scanning; never edited by hand, never relied on as
authoritative. If it disagrees with the vault, the vault wins — regenerate.

A note counts as a PROBLEM note iff its body contains a line that is
exactly `***` (the problem/conjecture separator). That filter naturally
excludes imported sources (e.g. Readwise/book notes) which have no `***`.

Usage:
    python problem_index.py <vault-root>
    python problem_index.py <vault-root> --out <path-to-index.json>
    python problem_index.py <vault-root> --exclude Attachments --exclude Interesting/Books

Output (JSON array), one object per problem note:
    {
      "name":     "<filename without .md>",
      "path":     "<path relative to vault root, forward slashes>",
      "problem":  "<problem side, above the first ***; may be empty>",
      "category": "<category: or collection: from frontmatter, or null>",
      "up":       ["<parent note name>", ...],   # [[..]] under up:
      "links":    ["<outbound link target>", ...], # unique, whole body
      "stub":     true|false   # true if the conjecture side is empty
    }

No third-party dependencies. Reuses split_note() from problem_half.py,
which must sit in the same directory.
"""

import json
import sys
from pathlib import Path

# One structural parser for the whole toolkit; see note_chunks.py. The `***`
# contract itself stays owned by problem_half.split_note().
sys.path.insert(0, str(Path(__file__).resolve().parent))
from problem_half import split_note  # noqa: E402
from note_chunks import body_offset, extract_links, parse_frontmatter  # noqa: E402


def index_note(path: Path, vault_root: Path):
    """Return an index record for a problem note, or None if not one."""
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    frontmatter, problem_side, has_sep = split_note(text)
    if not has_sep:
        return None  # not a problem note

    category, up = parse_frontmatter(frontmatter or "")

    # Conjecture side = everything below the first ***; used only to tell
    # a stub from a developed note and to harvest links living in prose.
    normalised = text.replace("\r\n", "\n").replace("\r", "\n")
    body = normalised[body_offset(normalised):]
    sep = body.find("\n***")
    conjecture = body[sep + 4:].strip() if sep != -1 else ""

    rel = path.relative_to(vault_root).as_posix()
    return {
        "name": path.stem,
        "path": rel,
        "problem": (problem_side or "").strip(),
        "category": category,
        "up": up,
        "links": extract_links(text),
        "stub": conjecture == "",
    }


def main():
    args = sys.argv[1:]
    excludes = []
    out_path = None
    positional = []
    i = 0
    while i < len(args):
        a = args[i]
        if a == "--out":
            out_path = args[i + 1]
            i += 2
        elif a == "--exclude":
            excludes.append(args[i + 1])
            i += 2
        else:
            positional.append(a)
            i += 1

    if not positional:
        print("usage: python problem_index.py <vault-root> "
              "[--out <index.json>] [--exclude <folder> ...]",
              file=sys.stderr)
        sys.exit(2)

    vault_root = Path(positional[0]).expanduser().resolve()
    if not vault_root.is_dir():
        print(f"error: not a directory: {vault_root}", file=sys.stderr)
        sys.exit(2)

    # Default excludes: Obsidian/tool internals, imported attachments, and the
    # basic-memory cross-app layer (kept separate from the live problem index).
    default_excludes = [".obsidian", ".trash", ".perspirator",
                        "Attachments", "memory"]
    exclude_norm = [e.replace("\\", "/").strip("/")
                    for e in (excludes + default_excludes)]

    records = []
    for path in sorted(vault_root.rglob("*.md")):
        rel = path.relative_to(vault_root).as_posix()
        if any(rel == e or rel.startswith(e + "/") for e in exclude_norm):
            continue
        rec = index_note(path, vault_root)
        if rec is not None:
            records.append(rec)

    payload = json.dumps(records, ensure_ascii=False, indent=2)
    if out_path:
        Path(out_path).expanduser().write_text(payload + "\n", encoding="utf-8")
        print(f"wrote {len(records)} problem notes to {out_path}",
              file=sys.stderr)
    else:
        print(payload)


if __name__ == "__main__":
    main()
