#!/usr/bin/env python3
"""
problem_index.py — a derived, disposable map of root Problem Notes.

Both Ingest (dedup before create) and Connect (find unlinked neighbours)
need a cheap, current answer to: "what problems already exist, and what do
they link to?" This script produces exactly that by scanning Markdown files
directly in the vault root. Nested source, template, memory, and transaction
trees are outside this index by construction.

It is NOT a source of truth. Markdown is the database. This index is
regenerated by re-scanning; never edited by hand, never relied on as
authoritative. If it disagrees with the vault, the vault wins — regenerate.

A note counts as a PROBLEM note iff its body contains a line whose trimmed
content is `***` outside a triple-backtick fence. That filter naturally
excludes imported sources (e.g. Readwise/book notes) which have no `***`.

Usage:
    python problem_index.py <vault-root>
    python problem_index.py <vault-root> --out <path-to-index.json>

Output (JSON array), one object per problem note:
    {
      "name":     "<filename without .md>",
      "path":     "<path relative to vault root, forward slashes>",
      "problem":  "<problem side, above the first ***; may be empty>",
      "category": "<category: or collection: from frontmatter, or null>",
      "up":       ["<parent note name>", ...],   # [[..]] under up:
      "links":    ["<outbound link target>", ...], # unique, whole body
      "stub":     true|false   # true if the conjecture side is empty
    }

No third-party dependencies. Reuses parse_note() from problem_half.py,
which must sit in the same directory.
"""

import argparse
import json
import sys
from pathlib import Path

# One structural parser for the whole toolkit; see note_chunks.py. The `***`
# contract itself stays owned by problem_half.parse_note().
sys.path.insert(0, str(Path(__file__).resolve().parent))
from problem_half import parse_note  # noqa: E402
from note_chunks import extract_links, parse_frontmatter  # noqa: E402


def index_note(path: Path, vault_root: Path):
    """Return an index record for a problem note, or None if not one."""
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    parsed = parse_note(text)
    frontmatter, problem_side = parsed["frontmatter"], parsed["problem"]
    if not parsed["has_separator"]:
        return None  # not a problem note

    category, up = parse_frontmatter(frontmatter or "")

    rel = path.relative_to(vault_root).as_posix()
    return {
        "name": path.stem,
        "path": rel,
        "problem": (problem_side or "").strip(),
        "category": category,
        "up": up,
        "links": extract_links(text),
        "stub": parsed["conjecture"] == "",
    }


def arguments(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vault_root", help="vault whose root Problem Notes are indexed")
    parser.add_argument("--out", help="write the disposable JSON index to this path")
    return parser.parse_args(argv)


def root_problem_records(vault_root):
    """Return structural Problem Notes directly inside ``vault_root``."""
    records = []
    for path in sorted(vault_root.glob("*.md")):
        rec = index_note(path, vault_root)
        if rec is not None:
            records.append(rec)
    return records


def main(argv=None):
    args = arguments(argv)
    vault_root = Path(args.vault_root).expanduser().resolve()
    if not vault_root.is_dir():
        print(f"error: not a directory: {vault_root}", file=sys.stderr)
        sys.exit(2)

    records = root_problem_records(vault_root)
    payload = json.dumps(records, ensure_ascii=False, indent=2)
    if args.out:
        Path(args.out).expanduser().write_text(payload + "\n", encoding="utf-8")
        print(f"wrote {len(records)} problem notes to {args.out}",
              file=sys.stderr)
    else:
        print(payload)


if __name__ == "__main__":
    main()
